- hosts: all
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Python 3 and pip
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip

    - name: Install Flask and Gunicorn
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - flask
        - gunicorn

    - name: Copy Flask application
      copy:
        src: ./app/
        dest: /home/vagrant/
